language: java
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2

before_install: cd server-java-issuetracker-restapi
install: true

script: mvn -B test  # mvn clean install is működne

before_deploy: cd server-java-issuetracker-restapi
deploy:
  provider: heroku
  api_key:
    secure: 66279025-e39d-44a7-b7bd-373f3f51c68e
  app: fswp-java-restapi-issuetracker
  on: main
